// Generated by the lithium symbol generator.
#include <lithium_symbol.hh>
#ifndef LI_SYMBOL_json_key
#define LI_SYMBOL_json_key
    LI_SYMBOL(json_key)
#endif

#ifndef LI_SYMBOL_my_param
#define LI_SYMBOL_my_param
    LI_SYMBOL(my_param)
#endif

#ifndef LI_SYMBOL_my_param2
#define LI_SYMBOL_my_param2
    LI_SYMBOL(my_param2)
#endif

#ifndef LI_SYMBOL_name
#define LI_SYMBOL_name
    LI_SYMBOL(name)
#endif

#ifndef LI_SYMBOL_type
#define LI_SYMBOL_type
    LI_SYMBOL(type)
#endif

